---
name: registripe_ticketselection
after: registripe
---
EventRegisterController:
  ticket_select_template: TicketCountSelections

EventTicket:
  selection_type: AttendeeTicketSelection

EventRegistration:
  calculation_components:
    - Cost

AttendeeTicketSelection:
  select_controller_action: attendee
  calculators:
    - SelectionCost
